FROM apache/airflow:slim-3.1.3-python3.12

USER root

RUN apt-get update && apt-get install -y \
    curl \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY --from=ghcr.io/astral-sh/uv:0.9.9 /uv /uvx /bin/

USER airflow

WORKDIR /opt/airflow

COPY --chown=airflow:root pyproject.toml uv.lock ./
COPY --chown=airflow:root ingestion/ ./ingestion/
COPY --chown=airflow:root dbt/ ./dbt/

RUN --mount=type=cache,target=/home/airflow/.cache/uv \
    uv sync --frozen --no-dev

