version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: xkcd_comics
        description: "Raw XKCD comic data from API"

models:
  - name: stg_xkcd_comics
    description: "Staging model for XKCD comics - normalized from raw JSON"
    columns:
      - name: comic_id
        description: "Unique identifier for the comic (from API 'num' field)"
        tests:
          - unique
          - not_null
      
      - name: title
        description: "Comic title"
        tests:
          - not_null
      
      - name: safe_title
        description: "Title without special characters"
      
      - name: alt_text
        description: "Alternative text for the comic image (hover text)"
      
      - name: img_url
        description: "URL to the comic image"
        tests:
          - not_null
      
      - name: transcript
        description: "Comic text transcript"
      
      - name: publish_date
        description: "Publication date parsed from year, month, day"
        tests:
          - not_null
      
      - name: publish_year
        description: "Publication year"
        tests:
          - not_null
      
      - name: publish_month
        description: "Publication month (1-12)"
        tests:
          - not_null
      
      - name: publish_day
        description: "Publication day (1-31)"
        tests:
          - not_null
      
      - name: link
        description: "Optional related link"
      
      - name: news
        description: "Optional news/announcement text"
      
      - name: load_ts
        description: "Timestamp when the comic was loaded into the database"
        tests:
          - not_null
      
      - name: load_id
        description: "UUID identifier for the batch load"
        tests:
          - not_null
